services:
  db:
    image: postgres:15-alpine
    container_name: shopapi_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shop
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data


  backend:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/shop
      - PYTHONUNBUFFERED=1
    depends_on:
      - db

volumes:
  db_data: